---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: alzlibtool
    env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X "github.com/Azure/alzlib/cmd/alzlibtool/command.version={{.Version}}" -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "alzlibtool"
    dir: cmd/alzlibtool
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
archives:
  - id: alzlibtool
    format: tar.gz
    builds:
      - alzlibtool
    name_template: "alzlibtool_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - format: zip
        goos: windows
    builds_info:
      group: root
      owner: root
      mode: 0755
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Doc updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 999
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^docs"
release:
  disable: false
milestones:
  - close: true
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
