---
name: Go test

on:
  push:
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    environment: test
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: actions/setup-go@v4
      name: setup go
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - uses: azure/login@v1
      name: Azure login
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - run: make test
      name: make test
      # Tests are run on Linux using make testcover
      if: matrix.os != 'ubuntu-latest'

    - run: make testrace
      name: make testrace
      if: matrix.os == 'ubuntu-latest'

    - run: make testcover
      name: make testcover
      if: matrix.os == 'ubuntu-latest'

    - uses: codecov/codecov-action@v3
      if: matrix.os == 'ubuntu-latest' && github.event_name != 'merge_group'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
